export const STACK = [
    {id :1 , title : "HTML" , photo:'/stack/html.svg'},
    {id :2 , title : "CSS" , photo:'/stack/css.svg'},
    {id :3 , title : "JavaScript" , photo:'/stack/javascript.svg'},
    {id :4 , title : "React" , photo:'/stack/reactjs.svg'},
    {id :5 , title : "Node.js" , photo:'/stack/nodejs.svg'},
    {id :6 , title : "Python" , photo:'/stack/python.svg'},
    {id :7 , title : "PhP" , photo:'/stack/php.svg'},
    {id :8 , title : "Laravel" , photo:'/stack/laravel.svg'},
    {id :9 , title : "TailwindCss" , photo:'/stack/tailwind.svg'},
    {id :10 , title : "ExpressJs" , photo:'/stack/expressjs.svg'},
    {id :11 , title : "Git" , photo:'/stack/git.svg'},
    {id :12 , title : "Github" , photo:'/stack/github.svg'},
    {id :13 , title : "Mongodb" , photo:'/stack/mongodb.svg'},
    {id :14 , title : "Mysql" , photo:'/stack/mysql.svg'},
    {id :15 , title : "Nextjs" , photo:'/stack/nextjs.svg'},
    {id :16 , title : "Typescript" , photo:'/stack/typescript.svg'},
    {id :17 , title : "C" , photo:'/stack/c.svg'},
    {id :18 , title : "Arduino" , photo:'/stack/arduino.svg'},
    {id :19 , title : "Wordpress" , photo:'/stack/wordpress.svg'},

]